// Tapping/Hold behavior settings
#define TAPPING_TERM 200
#define AUTO_SHIFT_TIMEOUT 200
#define AUTO_SHIFT_NO_SETUP
#define NO_AUTO_SHIFT_SPECIAL
#define TAPPING_CHORDAL_HOLD
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

// RGB settings
#define RGB_MATRIX_TIMEOUT 60000
#define RGB_MATRIX_SLEEP

// Split sync settings
#define DRIVER_LED_TOTAL 44
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_TRANSPORT_MIRROR
